let promptList: Array<string> = [
  "Karaoke",
  "Baking",
  "Playing board games",
  "Playing video games",
  "Going to the movies",
  "Walking on the beach",
  "Skiing",
  "Snowboarding",
  "Going to the gym",
  "Going to the park",
  "Shopping",
  "Cooking",
  "Driving",
  "Partying",
  "Cheap wine",
  "Stargazing",
  "Starbucks",
  "Netflix and chill",
  "Cookies",
  "Wine and cheese",
  "Hiking",
  "Camping",
  "Scuba diving",
  "Skydiving",
  "Bungee jumping",
  "Rock climbing",
  "Ice skating",
  "Playing the piano",
  "Musicals",
  "Visiting museums",
  "One night stands",
  "Swimming in the ocean",
  "Going on a cruise",
  "Road trip",
  "Photography",
  "Painting",
  "Art and crafts",
  "Reading",
  "Writing",
  "Playing sports",
  "Coffee",
  "Tea",
  "Beer",
  "Mac and cheese",
  "Salsa dancing",
];

export default promptList;
